version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./multivendor-ecommerce:/app
      - ./media:/app/media
      - ./static:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=multivendordb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=yourpassword

volumes:
  postgres_data: