version: '3.8'

services:
  db:
    image: postgres:13
    container_name: multivendor-psql-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: multivendor-django-web
    volumes:
      - ./multivendor-ecommerce:/app
      - ./media:/app/media
      - ./static:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
      while ! nc -z db 5432;
      do
        echo 'Waiting for PostgreSQL...';
        sleep 1;
      done;
      echo 'PostgreSQL started';
      python manage.py migrate;
      python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data: